# Research question
In this analysis, we build various Bayesian hierarchical models to assess data obtained through the RN4CAST study. This is a a 3-year project (2009–2011) nurse workforce study involving 33,731 registered nurses in 2169 nursing units in 486 hospitals in 12 European countries. For more information on the RN4CAST study, see Sermeus et al. (2011).[[1] Sermeus W, Aiken L, Van den Heede K, Rafferty A, Griffiths P, Moreno-Casbas M, Busse R, Lindqvist R, Scott A, Bruyneel L, Brzostek T, Kinnunen J, Schubert M, Schoonhoven L, Zikos D, RN4CAST consortium. Nurse forecasting in Europe (RN4CAST): rationale, design and methodology. BMC Nursing 2011; 10(1):6.][1]
For this project, the analysis is limited to data from 30 Belgian hospitals. 

The data are hierarchical with the nurses nested in nursing units nested in hospitals. The outcome variable is the reduced personal accomplishment (PA) dimension of burnout. It measures the feelings of reduced competence and successful achievement in the tasks the nurse is performing. High values of this measure indicate strong burnout.
Some covariates were recorded at the three levels of the data to predict the PA:
- Nurse level: experience (years of employment), full time nurse (0=no, 1=yes)
- Nursing unit level: surgical unit (1=yes, 0=no), work environment index, high values reflect a positive environment
- Hospital level: technical hospital (1=yes,0=no), teaching/university hospital (1=yes,0=no), number of beds


# Preprocessing and data exploration
The data file (i.e. `burnoutPA.txt`) contained two empty columns, which we deleted. 

The dataset has 1118 observations of the following variables and the following 10 variables:

**Nurse level**

-   `expe`: experience (years of employment)
-   `full`: full time nurse indicator (0/1)
-   `pa`: reduced personal accomplishment (PA) dimension of burnout (higher values indicate a higher burnout / reduction in PA)

**Nursing unit level**

-   `unit`: a nursing unit identifier
-   `unitsur`: surgical unit indicator (0/1)
-   `we`: work environment index (higher values indicate a more positive work environment)

**Hospital level**

-   `hosp`: a hospital identifier
-   `tech`: technical hospital indicator (0/1)
-   `teach`: teaching/university hospital indicator (0/1)
-   `beds`: number of beds

We recoded the data for the various variables where necessary (e.g. to obtain factors and integer values). 
Visual inspection of the outcome variable PA showed that the distribution of PA is skewed, with only very few large values.
Since we will apply vague priors, we standardise the continuous variables `expe`, `we` and `beds`.


# Questions
## Part 1
**Although the variable PA does not correspond to count data, a Poisson model will be
fitted for the purpose of this exercise.**

**Fit a three-level Poisson random intercept model, with nursing unit representing the level 2
random intercept and hospital representing the level 3 random intercept. Assume normal
distributions for the random intercepts.**

- **Take vague priors for all model parameters. Determine whether an inverse gamma or a uniform prior is most appropriate for the variability parameter of the random intercepts.**

The random intercepts model we fit here partitions the total variance in variance between hospitals $\epsilon_{h}\sim N(0,\sigma_h^2)$, variance between units within a hospital $\epsilon_{h,u}\sim N(0,\sigma_{h,u}^2)$, and residual variance $\epsilon_{h,u,n}$.

- **First, fit a model without the covariates and check convergence using classical diagnostics.**

As we are asked to model the dependent variable personal accomplishment $Y$ as a Poisson random variable, we use the exponential link function to obtain the following equation:

$$Y=e^{\beta_0+\epsilon_{h}+\epsilon_{h,u}+\epsilon_{h,u,n}}$$

- **Rank the hospitals according to their random effect (in WinBUGS it is possible with the rank option). Are there hospitals with important differences in the PA baseline level?**

- **In a second step, include the covariates. Are there hospitals genuinely different with respect to the PA level after adjusting for the covariates in the model?**

- **Check with DIC whether the inclusion of the covariates improves the fit with respect to the baseline model. Determine what variables to include using this selection criterion.**

- **Give all necessary posterior summary measures of the relevant parameters.**

- **Hint: Standardize all numeric covariates to improve convergence of the MCMC procedure and give initial values to the regression coefficients and parameters related to variances of random effects.**

## Part 2
**In some cases, there is overdispersion compared to what we would be expect in a Poisson model.**

- **Check whether a negative binomial distribution for PA is better than a Poisson distribution.**

- **Motivate your conclusion.**





[1]: https://bmcnurs.biomedcentral.com/articles/10.1186/1472-6955-10-6 "Sermeus et al. (2011)."