name: bookdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  bookdown:
    name: render
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install JAGS
        run: brew install jags
      - uses: r-lib/actions/setup-renv@v2
      - name: Render book
        run: Rscript -e 'bookdown::render_book("src/index.Rmd", "bookdown::pdf_book")'
      - uses: actions/upload-artifact@v3
        with:
          name: _main.pdf
          path: out/_main.pdf